name: CD

on:
  release:
    types:
    - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Tar x86_64 binary
      run: tar -czvf ob-format-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release ob-format

    - name: Zip windows binary
      run: zip -j ob-format-windows.zip target/x86_64-pc-windows-gnu/release/ob-format.exe

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 ob-format-gnu-linux-x86_64.tar.gz > ob-format-gnu-linux-x86_64.tar.gz.sha256
        shasum -a 256 ob-format-windows.zip > ob-format-windows.zip.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["ob-format-gnu-linux-x86_64.tar.gz", "ob-format-windows.zip", "ob-format-gnu-linux-x86_64.tar.gz.sha256", "ob-format-windows.zip.sha256"]'

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install rustup targets
      run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

    - name: Build the executable
      run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

    - name: Zip x86_64 binary
      run: tar -czvf ob-format-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release ob-format

    - name: Zip arm64 binary
      run: tar -czvf ob-format-macos-aarch64.tar.gz -C target/aarch64-apple-darwin/release ob-format

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 ob-format-macos-x86_64.tar.gz > ob-format-macos-x86_64.tar.gz.sha256
        shasum -a 256 ob-format-macos-aarch64.tar.gz > ob-format-macos-aarch64.tar.gz.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["ob-format-macos-x86_64.tar.gz", "ob-format-macos-aarch64.tar.gz", "ob-format-macos-x86_64.tar.gz.sha256", "ob-format-macos-aarch64.tar.gz.sha256"]'

